# Generated by Django 2.2.4 on 2021-02-06 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 20, 1, 34, 920948), verbose_name='date published'),
        ),
    ]
